=== AdamMata/WAI_HiH/Projekt/front/src/XML/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="games">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="game" type="game-type"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="game-type">
        <xs:sequence>
            <xs:element name="image" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:anyURI">
                            <xs:attribute name="type" type="xs:token"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="contributors" type="contributors-type"></xs:element>
            <xs:element name="requirements" type="requirements-type"></xs:element>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="contributors-type">
        <xs:sequence>
            <xs:element name="author" maxOccurs="unbounded" type="author-type"/>
            <xs:element name="publisher" type="xs:string"/>
            <xs:element name="release" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="stage" type="release-stage-attribute"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>      
    </xs:complexType>

    <xs:complexType name="author-type" mixed="true">
        <xs:sequence>
            <xs:element name="link" type="link-type"/>
        </xs:sequence>    
        <xs:attribute name="type" type="author-type-attribute"></xs:attribute>        
    </xs:complexType>

    <xs:complexType name="link-type">
        <xs:simpleContent>
            <xs:extension base="xs:anyURI"></xs:extension>
        </xs:simpleContent>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="website"/>
                    <xs:enumeration value="community"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- <xs:simpleType name="link"></xs:simpleType> -->

    <xs:simpleType name="author-type-attribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="studio"/>
            <xs:enumeration value="indie"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="release-stage-attribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="early access"></xs:enumeration>
            <xs:enumeration value="full"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="requirements-type">
        <xs:sequence>
            <xs:element name="platforms">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="platform" type="platform-type" maxOccurs="unbounded">
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="engine">

            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="platform-type">
        <xs:simpleContent>
            <xs:extension base="platform-version">
                <xs:attribute name="system">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Windows"></xs:enumeration>
                            <xs:enumeration value="Xbox"></xs:enumeration>
                            <xs:enumeration value="PlayStation"></xs:enumeration>
                            <xs:enumeration value="Linux"></xs:enumeration>
                            <xs:enumeration value="MacOS"></xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="platform-version">
        <xs:union memberTypes="
            xs:nonNegativeInteger
            xs:token
            empty
        "/>
    </xs:simpleType>
    <xs:simpleType name="empty">
        <xs:restriction base="xs:string">
            <xs:maxLength value="0"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== AdamMata/WAI_HiH/Projekt/front/src/XML/data.xml
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <game title="Satisfactory">
        <image type="logo">images/Satisfactory-logo.jpg</image>
        <contributors>
            <author type="studio">
                Coffee Stain Studios
                <link type="website">https://www.coffeestainstudios.com/</link>
            </author>
            <publisher>
                Coffee Stain Publishing
            </publisher>
            <release stage="early access">
                2019-03-19
            </release>
        </contributors>
        <requirements>
            <platforms>
                <platform system="Windows">7</platform>
                <platform system="Windows">8</platform>
                <platform system="Windows">10</platform>
                <platform system="Windows">11</platform>
            </platforms>
            <engine system="Unreal Engine"/>
        </requirements>
        <genres>
            <genre category="simulation">factory-building</genre>
            <genre category="simulation">sandbox</genre>
            <genre>third-person</genre>
        </genres>
    </game>
    <game title="Ultrakill">
        <image type="logo">images/Ultrakill-logo.jpg</image>
        <contributors>
            <author type="indie">
                Arsi "Hakita" Patala
            </author>
            <publisher>
                New Blood Interactive
                <link type="website">https://newblood.games/</link>
            </publisher>
            <release stage="early access">
                2020-09-03
            </release>
        </contributors>
        <requirements>
            <platforms>
                <platform system="Windows">7</platform>
                <platform system="Windows">8</platform>
                <platform system="Windows">10</platform>
                <platform system="Windows">11</platform>
            </platforms>
            <engine system="Unity"/>
        </requirements>
        <genres>
            <genre category="shooter">movement-shooter</genre>
            <genre category="shooter">boomer-shooter</genre>
            <genre>first-person</genre>
        </genres>
    </game>
    <game title="Prison Architect">
        <image type="logo">images/Prison_Architect-logo.jpg</image>
        <contributors>
            <author type="studio">
                Introversion Software
                <link type="website">https://www.introversion.co.uk/introversion/</link>
            </author>
            <publisher>
                Paradox Interactive
            </publisher>
            <release stage="full">
                2015-10-06
            </release>
        </contributors>
        <requirements>
            <platforms>
                <platform system="Windows">7</platform>
                <platform system="Windows">8</platform>
                <platform system="Windows">10</platform>
                <platform system="Windows">11</platform>

                <platform system="MacOS"></platform>
                <platform system="Linux"></platform>
                <platform system="PlayStation">4</platform>
                <platform system="Xbox">360</platform>
                <platform system="Xbox">One</platform>
            </platforms>
        </requirements>
        <genres>
            <genre category="simulation">business-management</genre>
            <genre category="simulation">sandbox</genre>
        </genres>
    </game>
</games>
